### ISSUE TITLE
ArgumentException: Could not find MaterialProperty: '_BlendMode', Num properties: 32

### ISSUE THREAD

**Issue by SDanton** [traggett/UnitySpriteShaders#13]
Here is the full exception...

ArgumentException: Could not find MaterialProperty: '_BlendMode', Num properties: 32
UnityEditor.ShaderGUI.FindProperty (System.String propertyName, UnityEditor.MaterialProperty[] properties, Boolean propertyIsMandatory) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/ShaderGUI.cs:47)
UnityEditor.ShaderGUI.FindProperty (System.String propertyName, UnityEditor.MaterialProperty[] properties) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/ShaderGUI.cs:36)
SpriteShaderGUI.FindProperties (UnityEditor.MaterialProperty[] props) (at Assets/Game/Shaders/Sprites/Editor/SpriteShaderGUI.cs:92)
SpriteShaderGUI.OnGUI (UnityEditor.MaterialEditor materialEditor, UnityEditor.MaterialProperty[] props) (at Assets/Game/Shaders/Sprites/Editor/SpriteShaderGUI.cs:63)
UnityEditor.MaterialEditor.PropertiesGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/MaterialEditor.cs:1459)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

... known issue? Anyway to work around it? Sorry, total newb when it comes to shaders. TIA!

**Comment by traggett** [comment]
Hey sorry for the late repsonse, this sounds super weird, are you using an old version of the shaders?
Could you try updating to latest?
It sounds like the ShaderGUI class is mismatched to the actual shaders.
