### ISSUE TITLE
Compilation errors in 2018.1.6f

### ISSUE THREAD

**Issue by karlmarxman** [traggett/UnitySpriteShaders#20]
I couldn't compile Windows standalone due to error 'unrecognized identifier 'SHADOW_COORDS' ' which happened anytime UNITY_LIGHT_ATTENUATION is called.  Google led me to try wrapping every call like this:

#if defined (SHADOWS_SCREEN) || defined (SHADOWS_DEPTH) || defined (SHADOWS_CUBE)
	UNITY_LIGHT_ATTENUATION(attenuation, input, input.posWorld.xyz);
#else 
	float attenuation = 1;
#endif

That allowed me to compile but unfortunately I don't think that worked correctly as it seems to have affected lighting quality even when clearly fully supported.

**Comment by traggett** [comment]
Hey, I'm not getting any compilation errors on latest with Unity 2018.2 so closing this :)
