### ISSUE TITLE
Pixellit cant batch ?

### ISSUE THREAD

**Issue by gotenxds** [traggett/UnitySpriteShaders#23]
Hello, first of all I want to say thank you for providing such awesome shaders for free!

Now I have a small question, I noticed that when I use the pixellit shader on materials, each object using the same a material has it's own batch. if I use the vertex shader I get 1 batch per material.

Is this a bug or a natural trade off of how the shader works?

**Comment by traggett** [comment]
Hey! Glad they're useful!

So yeah I'm afraid pixel-lit objects can't be batched if they are effected by multiple lights using forward rendering - this true no matter what shaders you use (try it with unity's standard shader and it should be exactly the same).
Vertex lit materials will as long as they have the same lights effecting them (each object can be effects by up to the 4 nearest lights).
