### ISSUE TITLE
In Unity 2018.3 sprite shape renderer color doesn't apply to shader.

### ISSUE THREAD

**Issue by sspike2** [traggett/UnitySpriteShaders#27]
when applied to sprite shape changing color in sprite shape renderer doesn't change color of the sprite shape.
![Screenshot (189)_LI](https://user-images.githubusercontent.com/34025910/54862849-ab73b280-4d66-11e9-9e1b-a0ecc12e3e20.jpg)

**Comment by traggett** [comment]
This should be working in latest.

**Comment by oddgoo** [comment]
This seems to be broken again. The colour is not being applied:
**Unity 2019.3.3f1**
**2D SpriteShape 3.0.9**
