### ISSUE TITLE
Is it possible to have it receive shadow?

### ISSUE THREAD

**Issue by JyuuAra** [traggett/UnitySpriteShaders#28]
Thank you for making this wonderful shader. 
I saw it in Spine2d forum and had been using it for a for a long time.
I really like it. Is it possible to have it receive shadow?

**Comment by traggett** [comment]
Hey! It can already receive shadows, however the material needs to write to depth for this to work.
Use the 'Write To Depth' tick box and choose a 'Depth Alpha Cutoff' value.
Ooh and also make sure your render has Receive Shows enabled too.
