### ISSUE TITLE
The shaders implicitly convert Standard Alpha to Premultiplied

### ISSUE THREAD

**Issue by ansstuff** [traggett/UnitySpriteShaders#29]
calculatePixel() function from ShaderShared.cginc multiplies color by alpha, thus making semitransparent sprites much darker than with Unity default sprite shader (which keeps pixel format intact).
Is it intentional or not? I think the color-blending function is not supposed to also convert pixel format, so I changed e.g.
`finalPixel.a = texureColor.a * color.a;     
finalPixel.rgb = (texureColor.rgb * color.rgb) * finalPixel.a;`
to
`finalPixel = texureColor * color;`

But I have to ask, what was the original rationale behind the conversion?

**Comment by traggett** [comment]
Hey! Good catch, that is a mistake - I've checked in a fix for it (it was also multiplying the color by the alpha in some other places when using standard alpha blending).
Thanks!
