### ISSUE TITLE
Error on shaders

### ISSUE THREAD

**Issue by dothem1337** [traggett/UnitySpriteShaders#3]
Hi

I imported the shaders in Unity and getting this error: "failed to open source file: 'ShaderMaths.cginc'" (gles3) and the same on (vulcan).

Any know issues on this?

**Comment by traggett** [comment]
Hey!
Hmm I did move all the .cginc files to a new CGIncluded folder - all the references are hooked up and are working for me though but sounds like there might be something still referencing the old location.

Are you using Spine? The Spine runtimes ship with a version of my shaders and it can cause conflicts if both the version included in Spine and the ones from this depot are in your project.
I'd try deleting the shaders that come with the Spine Unity runtimes and then reimport these ones to make sure its the latest version of the shaders in your project.

**Comment by dothem1337** [comment]
Yes I'm using Spine normaly, but in this case I tried to use it standalone to reproduce my problem. I have flickering (sprites dissapears, appears) on mobile phones. So I tried to use the standalone Shaders. Bot there are not both. I checked this. I think it's a bug on Unity, that the flickering appears.

**Comment by alastaira** [comment]
I got this error too, and have never used Spine. However, I simply ignored it and now it seems to have gone away (note that I'm not targetting GLES3 or Vulcan platforms though)

**Comment by traggett** [comment]
Hey! Just to check, are people still getting this on latest? All the shaders should be pointing to the correct folder now so hopefully this issue is all sorted :)
