### ISSUE TITLE
Sprites in Shadow apply Color Adjustment twice

### ISSUE THREAD

**Issue by pwn4** [traggett/UnitySpriteShaders#30]
Fantastic shaders btw. Really really awesome. This is a bug where materials will have color adjustment applied twice when they enter shadow areas. Looks funky, but causes problems when you're shifting hue.

Example:

Make a spriterenderer, attach a material with Pixel Lit shader, set hue to -0.28 (NOT -0.5, which is more confusing). When the material is moved under shadow, it will change to a different hue than you had set.

Problem (I think?) is in SpritePixelLighting.cginc:
```
fixed4 fragAdd(VertexOutput input) : SV_Target
{
	fixed4 texureColor = calculateTexturePixel(input.texcoord);
	
// THIS MUST BE COMMENTED OUT OR REMOVED
/*#if defined(_COLOR_ADJUST)
	texureColor = adjustColor(texureColor);
#endif*/ // _COLOR_ADJUST	
```

The adjustColor call here (and probably in a couple other places) should be removed, since it's already called inside calculateTexturePixel. If you have a hue value that's not an extreme (like 0.5) then you will get a hue shift. If you have a hue like -0.5 set, then it will look like the color adjustment suddenly turns off in shadow because the offset is just correct to bring hue delta back to 0 when applied twice.

I commented this out myself locally, and observed that the hue is preserved now when the material enters a shadow area. Thanks!

**Comment by traggett** [comment]
Hey! Good spot!! It was indeed doing it twice, thanks so much for flagging it, should be fixed now :)
