### ISSUE TITLE
Demo Project

### ISSUE THREAD

**Issue by hammackj** [traggett/UnitySpriteShaders#4]
Could you post a demo project of the robot?

Thanks.

**Comment by pharan** [comment]
What robot?

**Comment by hammackj** [comment]
In the readme there is a picture of the robot from the 2d assets being used
with the shader.

**Comment by alastaira** [comment]
That's the RobotBoy from the Unity standard assets. 
Assets -> Import Package -> 2D

**Comment by traggett** [comment]
Hey! Yeah like alastaira says its just Unitys own robot with these shaders applied to its material. 

A demo project showing features off would be great but I haven't had time yet - hopefully the material GUI is fairly straightforward to use by its self though - I've tried to make it mimic unitys standard shader to make it easier to understand.
