### ISSUE TITLE
CPU Spikes from Shader.EditorLoadVariant

### ISSUE THREAD

**Issue by alastaira** [traggett/UnitySpriteShaders#5]
I recently upgraded to the latest version of the UnitySpriteShaders package and also replaced all the previous sprite materials in my project to use either the Sprite (Vertex Lit) or Sprite (Pixel Lit) shader variants. However, I'm now noticing some fairly frequent extreme spikes in CPU in playmode from Shader.EditorLoadVariant which I haven't noticed before. Not sure if this is resulting from the upgrade to the newer version, or because I simply have more sprites in my scene using the shaders than I did previously.

![shadervariantspike](https://cloud.githubusercontent.com/assets/901056/23338312/4570438c-fbff-11e6-9840-bf35441cb6f3.jpg)

I'm not using lots of variations - some sprites are pixel lit, some vertex lit, some sprites have a normal map, some don't, some have an emission map, some don't. Other than that, they're all identical I believe. I have tried tracking all the used shader variants in the Graphics tab and adding them to the preloaded shader variant collection, but this seemed to make no difference.

**Comment by traggett** [comment]
Hey! Yeah I get quite nasty spikes when a new shader is compiled during runtime. I think compilation time goes up dramatically when the number of keywords hits a certain number. 
However, yeah the way of solving this should be doing what you're doing - creating a preloaded shader variant collection.
That def made a difference for me - can you check the shader collection and have a look to see the shaders match the combo's of what you're using?
