### ISSUE TITLE
Unity 5.5.3f1 - flipped lighting again (exception made when in edit/play mode on Unity)

### ISSUE THREAD

**Issue by NeatWolf** [traggett/UnitySpriteShaders#6]
Hi Todd,

I had your shaders consistently working with flipped normals (0,0,1) on Unity 5.4.2. And, found no solution since you all were using 5.5

Now I switched to 5.5.3f1, and the shaders are correctly working only in the editor (0,0,-1), but  on Android/iOS, they're lit from the opposite side again!

So I'm forced to always use (0,0,1) in the editor to produce working build, having to continuously flip normals while editing.
I tried different workarounds for runtime flipping but they're all too heavy for mobile.

Could you please have a look at the shaders again?

**Comment by NeatWolf** [comment]
Addendum:

It works with correct normals in the Unity Editor, and on iPhone4s or lower.
On Android and iPhone5s or higher they're flipped.

**Comment by traggett** [comment]
Hey NeatWolf, do the latest shaders fix the lighting issues on Android and iPhone?
