### ISSUE TITLE
Shaders are broken after upgrade to 5.6

### ISSUE THREAD

**Issue by alastaira** [traggett/UnitySpriteShaders#7]
Just upgraded my project from Unity 5.5 to 5.6, and also downloaded the latest version of the UnitySpriteShaders archive, and it seems like this has broken all the sprite materials in my project - specifically, there is no alpha cutoff and all lighting seems all wrong - see below:

Unity 5.5.2f1:
![5 5](https://cloud.githubusercontent.com/assets/901056/25073251/9513e09a-22da-11e7-93be-7dcfd250bb78.png)

Unity 5.6.0f3:
![5 6](https://cloud.githubusercontent.com/assets/901056/25073254/a9aeb70a-22da-11e7-841d-ae5d5a13cd5b.png)

I've also tried creating a brand new material in the new project, but that seems wrong as well. 

I'm guessing it's related to the same issues described in (the first of which also proposes a solution):
 - http://answers.unity3d.com/questions/1333938/custom-sprite-shader-works-in-55-not-56.html
 - http://answers.unity3d.com/questions/1334800/sprite-shader-not-working-in-56.html

**Comment by traggett** [comment]
Hey! Cripes yeah I just tried this and got the same results.
I've changed the shaders to deal with external alpha textures in the same way Unitys shaders do now in Unity 5.6 and that seems to fix it, could you get latest and see if its working for you now too?

**Comment by alastaira** [comment]
Hey - yep, that seems to have fixed it again. Thanks so much for the super-speedy attention! ;)
