### ISSUE TITLE
Add a list of property id strings in Readme

### ISSUE THREAD

**Issue by pharan** [traggett/UnitySpriteShaders#9]
Hey @traggett!

Just a heads up! I'm going to do a PR to add property name strings to the readme so people who want to use MaterialPropertyBlocks or modify Material properties in code can do so. (eg, for transiently setting or animating the overlay color.)

This can particularly be an issue for newbies or people who have ShaderForge or something similar installed, where they may not be able to see the properties listed in the inspector.

I hope you have a chance to check and merge it!

**Comment by pharan** [comment]
Attaching screenshots of the inspector for now.

![unity_2017-05-24_14-24-01](https://cloud.githubusercontent.com/assets/1911082/26389498/ce157938-408c-11e7-8838-cef3836eee5c.png)
![unity_2017-05-24_14-23-43](https://cloud.githubusercontent.com/assets/1911082/26389499/ce17c5bc-408c-11e7-8492-4ed5dcf0dfc3.png)
![unity_2017-05-24_14-23-49](https://cloud.githubusercontent.com/assets/1911082/26389500/ce1f77c6-408c-11e7-8548-14e8b42ae812.png)

**Comment by traggett** [comment]
Hey! Nice, yeah good idea I will try and merge it in :)

**Comment by pharan** [comment]
https://github.com/traggett/UnitySpriteShaders/pull/10
